#!/usr/bin/env groovy

pipeline {
    agent any
    
    triggers { pollSCM('* * * * *') }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/bourbon-vanilla/jenkins-spring-petclinic.git'
            }
        }
        stage('Build') {
            steps {
                sh './mvnw clean package'
            }
            post {
            // If Maven was able to run the tests, even if some of the test
            // failed, record the test results and archive the jar file.
                always {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                }
                changed {
                    emailext subject: "Job \'${JOB_NAME}\' (${BUILD_NUMBER}) ${currentBuild.result}",
                        body: "Please go to ${BUILD_URL} for details", 
                        attachLog: true, 
                        compressLog: true, 
                        recipientProviders: [upstreamDevelopers(), requestor()]
                }
            }
        }
    }
}
